comp:
        actual:
                files:
                    - "bin/fesom.x"
        check:
                comp: all
run:
        actual:
                errors:
                    - "MISSING FILES"
                files:
                    - "outdata/fesom/*.fesom.*.nc"
                    - "restart/fesom/fesom.*.oce.nc*"
                    - "restart/fesom/fesom.*.ice.nc*"
        check:
                files: []
                compare: []
