comp:
        actual:
                files:
                    - "bin/fesom.x"
        check:
                comp: all
run:
        actual:
                files: []
        check:
                files: []
                compare: []
