comp:
        actual:
                files:
                    - "bin/fesom.x"
                    - "bin/echam6"
        check:
                compare:
                    - "comp*echam*.sh"
                    - "comp*fesom*.sh"
run:
        actual:
                errors:
                    - "MISSING FILES"
                files:
                    - "restart/echam/restart*.nc*"
                    - "restart/fesom/fesom.*.oce.restart.nc*"
                    - "restart/fesom/fesom.*.ice.restart.nc*"
                    - "outdata/echam/*"
                    - "outdata/fesom/*.fesom.*.nc"
        check:
                compare:
                   - ""
computer:
        - mistral
